import type {
  LLMProvider,
  AgentConfig,
  Plugin,
  Integration,
  BillingPlan,
  UsageStat,
} from "./types";

export const defaultProviders: LLMProvider[] = [
  {
    id: "openai",
    name: "OpenAI",
    logo: "🤖",
    enabled: true,
    apiKey: "",
    models: ["gpt-4o", "gpt-4o-mini", "gpt-4-turbo", "gpt-3.5-turbo"],
    selectedModel: "gpt-4o",
    description: "Industry-leading language models with broad capability.",
  },
  {
    id: "anthropic",
    name: "Anthropic",
    logo: "🧠",
    enabled: false,
    apiKey: "",
    models: [
      "claude-3-5-sonnet-20241022",
      "claude-3-5-haiku-20241022",
      "claude-3-opus-20240229",
    ],
    selectedModel: "claude-3-5-sonnet-20241022",
    description: "Safety-focused AI with strong reasoning capabilities.",
  },
  {
    id: "google",
    name: "Google Gemini",
    logo: "✨",
    enabled: false,
    apiKey: "",
    models: ["gemini-2.0-flash", "gemini-1.5-pro", "gemini-1.5-flash"],
    selectedModel: "gemini-2.0-flash",
    description: "Google's multimodal AI with long context windows.",
  },
  {
    id: "mistral",
    name: "Mistral AI",
    logo: "🌊",
    enabled: false,
    apiKey: "",
    models: ["mistral-large-latest", "mistral-small-latest", "open-mixtral-8x22b"],
    selectedModel: "mistral-large-latest",
    description: "Open and efficient European AI models.",
  },
  {
    id: "groq",
    name: "Groq",
    logo: "⚡",
    enabled: false,
    apiKey: "",
    models: ["llama-3.3-70b-versatile", "llama-3.1-8b-instant", "mixtral-8x7b-32768"],
    selectedModel: "llama-3.3-70b-versatile",
    description: "Ultra-fast inference with open-source models.",
  },
];

export const defaultAgentConfig: AgentConfig = {
  framework: "openai-agents",
  maxIterations: 10,
  temperature: 0.7,
  systemPrompt:
    "You are a helpful AI assistant. Answer questions accurately and concisely.",
  memoryEnabled: true,
  streamingEnabled: true,
};

export const defaultPlugins: Plugin[] = [
  {
    id: "web-search",
    name: "Web Search",
    description: "Allow your agent to search the web for up-to-date information.",
    category: "Tools",
    enabled: true,
    icon: "🔍",
    version: "1.2.0",
    config: { engine: "google", maxResults: "5" },
  },
  {
    id: "code-interpreter",
    name: "Code Interpreter",
    description: "Execute Python code in a sandboxed environment.",
    category: "Tools",
    enabled: true,
    icon: "💻",
    version: "2.0.1",
    config: { timeout: "30", memoryMb: "512" },
  },
  {
    id: "file-reader",
    name: "File Reader",
    description: "Read and parse PDF, Word, Excel, and other document formats.",
    category: "Tools",
    enabled: false,
    icon: "📄",
    version: "1.0.5",
  },
  {
    id: "image-analysis",
    name: "Image Analysis",
    description: "Analyze and describe images using vision capabilities.",
    category: "Vision",
    enabled: true,
    icon: "🖼️",
    version: "1.1.0",
  },
  {
    id: "rag",
    name: "RAG / Vector Store",
    description: "Retrieval-Augmented Generation with your own documents.",
    category: "Memory",
    enabled: false,
    icon: "📚",
    version: "3.0.0",
    config: { chunkSize: "512", overlap: "50", topK: "5" },
  },
  {
    id: "memory-store",
    name: "Persistent Memory",
    description: "Remember past conversations and user preferences across sessions.",
    category: "Memory",
    enabled: true,
    icon: "🧩",
    version: "1.4.2",
  },
  {
    id: "email",
    name: "Email",
    description: "Send and read emails on behalf of the user.",
    category: "Communication",
    enabled: false,
    icon: "📧",
    version: "1.0.0",
  },
  {
    id: "calendar",
    name: "Calendar",
    description: "Manage calendar events, reminders, and scheduling.",
    category: "Productivity",
    enabled: false,
    icon: "📅",
    version: "1.0.3",
  },
];

export const defaultIntegrations: Integration[] = [
  {
    id: "notion",
    name: "Notion",
    description: "Connect your Notion workspace to sync pages, databases, and notes.",
    icon: "📝",
    connected: false,
    category: "Productivity",
    config: { workspaceId: "", token: "" },
  },
  {
    id: "slack",
    name: "Slack",
    description: "Deploy your AI assistant as a Slack bot in your workspace.",
    icon: "💬",
    connected: false,
    category: "Communication",
    config: { botToken: "", signingSecret: "" },
  },
  {
    id: "github",
    name: "GitHub",
    description: "Access repositories, issues, and pull requests through your agent.",
    icon: "🐙",
    connected: false,
    category: "Development",
    config: { token: "" },
  },
  {
    id: "google-drive",
    name: "Google Drive",
    description: "Read and write files in your Google Drive.",
    icon: "📁",
    connected: false,
    category: "Storage",
    config: { clientId: "", clientSecret: "" },
  },
  {
    id: "linear",
    name: "Linear",
    description: "Create and manage Linear issues and projects with your agent.",
    icon: "📐",
    connected: false,
    category: "Development",
    config: { apiKey: "" },
  },
  {
    id: "hubspot",
    name: "HubSpot",
    description: "Access CRM data, contacts, and deals from HubSpot.",
    icon: "🏢",
    connected: false,
    category: "CRM",
    config: { apiKey: "" },
  },
  {
    id: "postgres",
    name: "PostgreSQL",
    description: "Query your PostgreSQL database directly through the agent.",
    icon: "🐘",
    connected: false,
    category: "Database",
    config: { connectionString: "" },
  },
  {
    id: "stripe",
    name: "Stripe",
    description: "Access payment data, customers, and subscriptions.",
    icon: "💳",
    connected: false,
    category: "Finance",
    config: { apiKey: "" },
  },
];

export const billingPlans: BillingPlan[] = [
  {
    id: "free",
    name: "Free",
    price: 0,
    period: "month",
    features: [
      "1 AI provider",
      "100 requests / month",
      "2 plugins",
      "Community support",
    ],
    current: false,
  },
  {
    id: "pro",
    name: "Pro",
    price: 29,
    period: "month",
    features: [
      "Unlimited AI providers",
      "10,000 requests / month",
      "All plugins",
      "5 integrations",
      "Priority support",
      "Custom system prompts",
    ],
    current: true,
  },
  {
    id: "enterprise",
    name: "Enterprise",
    price: 149,
    period: "month",
    features: [
      "Everything in Pro",
      "Unlimited requests",
      "Unlimited integrations",
      "SSO & team management",
      "Dedicated support",
      "SLA guarantee",
      "On-premise deployment",
    ],
    current: false,
  },
];

export const usageStats: UsageStat[] = [
  { label: "API Requests", used: 4821, limit: 10000, unit: "requests" },
  { label: "Tokens Used", used: 1240000, limit: 5000000, unit: "tokens" },
  { label: "Active Plugins", used: 4, limit: 8, unit: "plugins" },
  { label: "Integrations", used: 2, limit: 5, unit: "integrations" },
];
